///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LaunchFSW
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Audiogram recording.
    /// </summary>
    [TestModule("aca7f612-7f8c-4f0b-ae61-a25110b95a89", ModuleType.Recording, 1)]
    public partial class Audiogram : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LaunchFSWRepository repository.
        /// </summary>
        public static LaunchFSWRepository repo = LaunchFSWRepository.Instance;

        static Audiogram instance = new Audiogram();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Audiogram()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Audiogram Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.Text' at Center.", repo.Smart_window.TextInfo, new RecordItemIndex(0));
            repo.Smart_window.Text.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.ContentTextBlock' at Center.", repo.Smart_window.ContentTextBlockInfo, new RecordItemIndex(2));
            repo.Smart_window.ContentTextBlock.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}' with focus on 'Smart_window'.", repo.Smart_window.SelfInfo, new RecordItemIndex(3));
            repo.Smart_window.Self.EnsureVisible();
            Keyboard.Press("{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}{Tab}{NumPad6}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.StandAloneAutomationIdsAudiogramAutomat' at Center.", repo.Smart_window.StandAloneAutomationIdsAudiogramAutomatInfo, new RecordItemIndex(4));
            repo.Smart_window.StandAloneAutomationIdsAudiogramAutomat.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StandAloneAutomationIdsDetailsAutomatio' at Center.", repo.StandAloneAutomationIdsDetailsAutomatioInfo, new RecordItemIndex(6));
            repo.StandAloneAutomationIdsDetailsAutomatio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(7));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.StandAloneAutomationIdsDetailsAutomatio1' at Center.", repo.Smart_window.StandAloneAutomationIdsDetailsAutomatio1Info, new RecordItemIndex(8));
            repo.Smart_window.StandAloneAutomationIdsDetailsAutomatio1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
