///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LaunchFSW
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchFSW recording.
    /// </summary>
    [TestModule("c331dfb7-4104-4d20-a956-6c75a441158d", ModuleType.Recording, 1)]
    public partial class LaunchFSW : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LaunchFSWRepository repository.
        /// </summary>
        public static LaunchFSWRepository repo = LaunchFSWRepository.Instance;

        static LaunchFSW instance = new LaunchFSW();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchFSW()
        {
            First_Name = "";
            Last_Name = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchFSW Instance
        {
            get { return instance; }
        }

#region Variables

        string _First_Name;

        /// <summary>
        /// Gets or sets the value of variable First_Name.
        /// </summary>
        [TestVariable("e1db671d-8e2e-4ce3-9099-a171f451fdee")]
        public string First_Name
        {
            get { return _First_Name; }
            set { _First_Name = value; }
        }

        string _Last_Name;

        /// <summary>
        /// Gets or sets the value of variable Last_Name.
        /// </summary>
        [TestVariable("dce57e45-0cf5-4184-91d3-3f2814e3a13f")]
        public string Last_Name
        {
            get { return _Last_Name; }
            set { _Last_Name = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\ReSound\\SmartFit\\SmartFitSA.exe' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\ReSound\\SmartFit\\SmartFitSA.exe", "", "C:\\Program Files (x86)\\ReSound\\SmartFit", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 12s.", new RecordItemIndex(1));
            Delay.Duration(12000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.StandAloneAutomationIdsAdd2Action' at Center.", repo.Smart_window.StandAloneAutomationIdsAdd2ActionInfo, new RecordItemIndex(2));
            repo.Smart_window.StandAloneAutomationIdsAdd2Action.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(3));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.StandAloneAutomationIdsProfileAutomatio1' at Center.", repo.Smart_window.StandAloneAutomationIdsProfileAutomatio1Info, new RecordItemIndex(4));
            repo.Smart_window.StandAloneAutomationIdsProfileAutomatio1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(5));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$First_Name'.", new RecordItemIndex(6));
            Keyboard.Press(First_Name);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Smart_window.StandAloneAutomationIdsProfileAutomatio' at Center.", repo.Smart_window.StandAloneAutomationIdsProfileAutomatioInfo, new RecordItemIndex(7));
            repo.Smart_window.StandAloneAutomationIdsProfileAutomatio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Last_Name'.", new RecordItemIndex(8));
            Keyboard.Press(Last_Name);
            Delay.Milliseconds(20);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
