///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LaunchFSW
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LaunchFSWRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bf05e781-27b0-430f-9b85-cc0db488c5ce")]
    public partial class LaunchFSWRepository : RepoGenBaseFolder
    {
        static LaunchFSWRepository instance = new LaunchFSWRepository();
        LaunchFSWRepositoryFolders.Smart_windowAppFolder _smart_window;
        LaunchFSWRepositoryFolders.SmartLauncherAppFolder _smartlauncher;
        LaunchFSWRepositoryFolders.SmartFitAppFolder _smartfit;
        LaunchFSWRepositoryFolders.Explorer1AppFolder _explorer1;
        LaunchFSWRepositoryFolders.TargetViewerAppFolder _targetviewer;
        LaunchFSWRepositoryFolders.WindowAppFolder _window;
        LaunchFSWRepositoryFolders.SomeFormAppFolder _someform;
        RepoItemInfo _menuautomationidsviewautomationidscoupInfo;
        RepoItemInfo _saveautomationidsperformsaveautomationiInfo;
        RepoItemInfo _standaloneautomationidsdetailsautomatioInfo;
        RepoItemInfo _windowautomationidscloseactionInfo;

        /// <summary>
        /// Gets the singleton class instance representing the LaunchFSWRepository element repository.
        /// </summary>
        [RepositoryFolder("bf05e781-27b0-430f-9b85-cc0db488c5ce")]
        public static LaunchFSWRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LaunchFSWRepository() 
            : base("LaunchFSWRepository", "/", null, 0, false, "bf05e781-27b0-430f-9b85-cc0db488c5ce", ".\\RepositoryImages\\LaunchFSWRepositorybf05e781.rximgres")
        {
            _smart_window = new LaunchFSWRepositoryFolders.Smart_windowAppFolder(this);
            _smartlauncher = new LaunchFSWRepositoryFolders.SmartLauncherAppFolder(this);
            _smartfit = new LaunchFSWRepositoryFolders.SmartFitAppFolder(this);
            _explorer1 = new LaunchFSWRepositoryFolders.Explorer1AppFolder(this);
            _targetviewer = new LaunchFSWRepositoryFolders.TargetViewerAppFolder(this);
            _window = new LaunchFSWRepositoryFolders.WindowAppFolder(this);
            _someform = new LaunchFSWRepositoryFolders.SomeFormAppFolder(this);
            _menuautomationidsviewautomationidscoupInfo = new RepoItemInfo(this, "MenuAutomationIdsViewAutomationIdsCoup", "/contextmenu[@automationid='' and @wpfnative='True']/menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerActionItemsAutomationIds.Coupler_OES']", 30000, null, "06277e6b-0442-4926-a654-5e27f78423e3");
            _saveautomationidsperformsaveautomationiInfo = new RepoItemInfo(this, "SaveAutomationIdsPerformSaveAutomationI", "/form[@name='ReSound Smart Fit 1.17']/button[@automationid='SaveAutomationIds.PerformSaveAutomationIds.ContinueAction']", 30000, null, "e1eeeb05-8704-42f6-b780-dfa1b71ae377");
            _standaloneautomationidsdetailsautomatioInfo = new RepoItemInfo(this, "StandAloneAutomationIdsDetailsAutomatio", "/form[@name='ReSound Smart Fit 1.17']/button[@automationid='StandAloneAutomationIds.DetailsAutomationIds.SaveAction']", 30000, null, "a1a3ba30-900e-4cfe-99b1-b021bd6c950c");
            _windowautomationidscloseactionInfo = new RepoItemInfo(this, "WindowAutomationIdsCloseAction", "/form[@name='ReSound Smart Fit 1.17']/button[@automationid='WindowAutomationIds.CloseAction']", 30000, null, "e2f8dd77-38b0-41a8-8bb5-2ab572580307");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bf05e781-27b0-430f-9b85-cc0db488c5ce")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MenuAutomationIdsViewAutomationIdsCoup item.
        /// </summary>
        [RepositoryItem("06277e6b-0442-4926-a654-5e27f78423e3")]
        public virtual Ranorex.MenuItem MenuAutomationIdsViewAutomationIdsCoup
        {
            get
            {
                 return _menuautomationidsviewautomationidscoupInfo.CreateAdapter<Ranorex.MenuItem>(true);
            }
        }

        /// <summary>
        /// The MenuAutomationIdsViewAutomationIdsCoup item info.
        /// </summary>
        [RepositoryItemInfo("06277e6b-0442-4926-a654-5e27f78423e3")]
        public virtual RepoItemInfo MenuAutomationIdsViewAutomationIdsCoupInfo
        {
            get
            {
                return _menuautomationidsviewautomationidscoupInfo;
            }
        }

        /// <summary>
        /// The SaveAutomationIdsPerformSaveAutomationI item.
        /// </summary>
        [RepositoryItem("e1eeeb05-8704-42f6-b780-dfa1b71ae377")]
        public virtual Ranorex.Button SaveAutomationIdsPerformSaveAutomationI
        {
            get
            {
                 return _saveautomationidsperformsaveautomationiInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The SaveAutomationIdsPerformSaveAutomationI item info.
        /// </summary>
        [RepositoryItemInfo("e1eeeb05-8704-42f6-b780-dfa1b71ae377")]
        public virtual RepoItemInfo SaveAutomationIdsPerformSaveAutomationIInfo
        {
            get
            {
                return _saveautomationidsperformsaveautomationiInfo;
            }
        }

        /// <summary>
        /// The StandAloneAutomationIdsDetailsAutomatio item.
        /// </summary>
        [RepositoryItem("a1a3ba30-900e-4cfe-99b1-b021bd6c950c")]
        public virtual Ranorex.Button StandAloneAutomationIdsDetailsAutomatio
        {
            get
            {
                 return _standaloneautomationidsdetailsautomatioInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The StandAloneAutomationIdsDetailsAutomatio item info.
        /// </summary>
        [RepositoryItemInfo("a1a3ba30-900e-4cfe-99b1-b021bd6c950c")]
        public virtual RepoItemInfo StandAloneAutomationIdsDetailsAutomatioInfo
        {
            get
            {
                return _standaloneautomationidsdetailsautomatioInfo;
            }
        }

        /// <summary>
        /// The WindowAutomationIdsCloseAction item.
        /// </summary>
        [RepositoryItem("e2f8dd77-38b0-41a8-8bb5-2ab572580307")]
        public virtual Ranorex.Button WindowAutomationIdsCloseAction
        {
            get
            {
                 return _windowautomationidscloseactionInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The WindowAutomationIdsCloseAction item info.
        /// </summary>
        [RepositoryItemInfo("e2f8dd77-38b0-41a8-8bb5-2ab572580307")]
        public virtual RepoItemInfo WindowAutomationIdsCloseActionInfo
        {
            get
            {
                return _windowautomationidscloseactionInfo;
            }
        }

        /// <summary>
        /// The Smart_window folder.
        /// </summary>
        [RepositoryFolder("b9d4415a-519a-4376-a30d-bb92f0511cbd")]
        public virtual LaunchFSWRepositoryFolders.Smart_windowAppFolder Smart_window
        {
            get { return _smart_window; }
        }

        /// <summary>
        /// The SmartLauncher folder.
        /// </summary>
        [RepositoryFolder("9a7a3d65-5cbd-4e5a-954d-c974fef3dab7")]
        public virtual LaunchFSWRepositoryFolders.SmartLauncherAppFolder SmartLauncher
        {
            get { return _smartlauncher; }
        }

        /// <summary>
        /// The SmartFit folder.
        /// </summary>
        [RepositoryFolder("38008620-1f1a-4578-b6a6-eefb8e3b7d4e")]
        public virtual LaunchFSWRepositoryFolders.SmartFitAppFolder SmartFit
        {
            get { return _smartfit; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("14e0119e-0a45-4136-9024-cf59fbb8a5c2")]
        public virtual LaunchFSWRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The TargetViewer folder.
        /// </summary>
        [RepositoryFolder("30213608-5b5a-467d-90fd-56a7f6a575c1")]
        public virtual LaunchFSWRepositoryFolders.TargetViewerAppFolder TargetViewer
        {
            get { return _targetviewer; }
        }

        /// <summary>
        /// The Window folder.
        /// </summary>
        [RepositoryFolder("3e58e746-2d81-46bf-82a4-e42589f514c9")]
        public virtual LaunchFSWRepositoryFolders.WindowAppFolder Window
        {
            get { return _window; }
        }

        /// <summary>
        /// The SomeForm folder.
        /// </summary>
        [RepositoryFolder("cf40f161-549b-409f-b42e-90ee0284e7c4")]
        public virtual LaunchFSWRepositoryFolders.SomeFormAppFolder SomeForm
        {
            get { return _someform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LaunchFSWRepositoryFolders
    {
        /// <summary>
        /// The Smart_windowAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9d4415a-519a-4376-a30d-bb92f0511cbd")]
        public partial class Smart_windowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _standaloneautomationidsprofileautomatioInfo;
            RepoItemInfo _standaloneautomationidsprofileautomatio1Info;
            RepoItemInfo _standaloneautomationidsadd2actionInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _contenttextblockInfo;
            RepoItemInfo _standaloneautomationidsaudiogramautomatInfo;
            RepoItemInfo _contenttextblock1Info;
            RepoItemInfo _menuautomationidsviewactionInfo;
            RepoItemInfo _standaloneautomationidsdetailsautomatio1Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _statemachineautomationidscontinueactionInfo;
            RepoItemInfo _contenttextblock2Info;
            RepoItemInfo _contenttextblock3Info;
            RepoItemInfo _contenttextblock4Info;
            RepoItemInfo _contenttextblock5Info;
            RepoItemInfo _contenttextblock6Info;
            RepoItemInfo _contenttextblock7Info;
            RepoItemInfo _navigationautomationidsmainautomationidInfo;
            RepoItemInfo _contenttextblock9Info;
            RepoItemInfo _contenttextblock10Info;
            RepoItemInfo _contenttextblock11Info;
            RepoItemInfo _contenttextblock12Info;
            RepoItemInfo _fittingautomationidsadvancedfeaturesautInfo;
            RepoItemInfo _fittingautomationidssaveactionInfo;
            RepoItemInfo _partscrollviewerInfo;
            RepoItemInfo _menuautomationidsfittingactionInfo;
            RepoItemInfo _savedtodatabaseInfo;
            RepoItemInfo _saveautomationidsperformsaveautomationi1Info;
            RepoItemInfo _testInfo;
            RepoItemInfo _patientInfo;
            RepoItemInfo _fitpatientInfo;
            RepoItemInfo _standaloneautomationidslistautomationidInfo;
            RepoItemInfo _standaloneautomationidslistautomationid1Info;
            RepoItemInfo _text3Info;
            RepoItemInfo _standaloneautomationidslistautomationid2Info;

            /// <summary>
            /// Creates a new Smart_window  folder.
            /// </summary>
            public Smart_windowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Smart_window", "/form[@automationid='WindowAutomationIds.StandAloneShell']", parentFolder, 30000, null, true, "b9d4415a-519a-4376-a30d-bb92f0511cbd", "")
            {
                _standaloneautomationidsprofileautomatioInfo = new RepoItemInfo(this, "StandAloneAutomationIdsProfileAutomatio", "text[@automationid='StandAloneAutomationIds.ProfileAutomationIds.LastNameField']", "text[@automationid='StandAloneAutomationIds.ProfileAutomationIds.LastNameField']", 30000, null, "cc32451e-c69a-46dd-9edc-321ab4b650d9");
                _standaloneautomationidsprofileautomatio1Info = new RepoItemInfo(this, "StandAloneAutomationIdsProfileAutomatio1", "text[@automationid='StandAloneAutomationIds.ProfileAutomationIds.FirstNameField']", "text[@automationid='StandAloneAutomationIds.ProfileAutomationIds.FirstNameField']", 30000, null, "1e0c93c9-9477-48f9-9032-385447cc6a24");
                _standaloneautomationidsadd2actionInfo = new RepoItemInfo(this, "StandAloneAutomationIdsAdd2Action", "button[@automationid='StandAloneAutomationIds.Add2Action']", "button[@automationid='StandAloneAutomationIds.Add2Action']", 30000, null, "836c2fbb-932f-413c-bef1-e63fc60abfad");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/listitem[@automationid='StandAloneAutomationIds.DetailsAutomationIds.AudiogramAction']/?/?/text[@automationid='Text']", ".//text[@name='Audiogram']", 30000, null, "51f143a3-1df0-4734-b387-d3ffc3af29b5");
                _contenttextblockInfo = new RepoItemInfo(this, "ContentTextBlock", "container[1]/text[27]", "container[1]/text[27]", 30000, null, "90070278-86eb-4ad8-abf6-e31d5669d47b");
                _standaloneautomationidsaudiogramautomatInfo = new RepoItemInfo(this, "StandAloneAutomationIdsAudiogramAutomat", "button[@automationid='StandAloneAutomationIds.AudiogramAutomationIds.CopyRightAction']", "button[@automationid='StandAloneAutomationIds.AudiogramAutomationIds.CopyRightAction']", 30000, null, "84546401-03d4-4bff-85d0-2adcd0a2157e");
                _contenttextblock1Info = new RepoItemInfo(this, "ContentTextBlock1", "?/?/text[@name='All']", "?/?/text[@name='All']", 30000, null, "f20ffcb6-95de-4c0b-83eb-266b9e7a134e");
                _menuautomationidsviewactionInfo = new RepoItemInfo(this, "MenuAutomationIdsViewAction", "?/?/menuitem[@automationid='MenuAutomationIds.ViewAction']", "?/?/menuitem[@automationid='MenuAutomationIds.ViewAction']", 30000, null, "7a87dcaa-fa41-47a7-9a6a-b9967893f094");
                _standaloneautomationidsdetailsautomatio1Info = new RepoItemInfo(this, "StandAloneAutomationIdsDetailsAutomatio1", "button[@automationid='StandAloneAutomationIds.DetailsAutomationIds.FitAction']", "button[@automationid='StandAloneAutomationIds.DetailsAutomationIds.FitAction']", 30000, null, "00b33339-f95d-46d6-9907-a5beb04cbe08");
                _text1Info = new RepoItemInfo(this, "Text1", "?/?/text[@name='Fit Patient']", "?/?/text[@name='Fit Patient']", 30000, null, "ae7293b6-3b45-46e9-a591-00714a2dcd18");
                _text2Info = new RepoItemInfo(this, "Text2", "text[@name='Physical Properties']", "text[@name='Physical Properties']", 10000, null, "bbb91551-0ce8-4738-94b6-5da061d7d504");
                _statemachineautomationidscontinueactionInfo = new RepoItemInfo(this, "StateMachineAutomationIdsContinueAction", "button[@automationid='StateMachineAutomationIds.ContinueAction']", "button[@automationid='StateMachineAutomationIds.ContinueAction']", 10000, null, "0e429078-8f8c-4b58-ac1b-9ff83b5dcc8d");
                _contenttextblock2Info = new RepoItemInfo(this, "ContentTextBlock2", "?/?/text[@name='250']", "?/?/text[@name='250']", 30000, null, "f3a1ef92-d0b8-4d54-ae8c-afd1ff9a91e1");
                _contenttextblock3Info = new RepoItemInfo(this, "ContentTextBlock3", "?/?/text[@name='500']", "?/?/text[@name='500']", 30000, null, "44890dbd-7b4e-45d5-b8a4-9bfb248f1687");
                _contenttextblock4Info = new RepoItemInfo(this, "ContentTextBlock4", "?/?/text[@name='750']", "?/?/text[@name='750']", 30000, null, "f56f212f-d437-40f4-97a2-0522b4518cc9");
                _contenttextblock5Info = new RepoItemInfo(this, "ContentTextBlock5", "?/?/text[@name='1K']", "?/?/text[@name='1K']", 30000, null, "99e625bd-bdbc-4873-91fc-330505f4e258");
                _contenttextblock6Info = new RepoItemInfo(this, "ContentTextBlock6", "?/?/text[@name='1.5K']", "?/?/text[@name='1.5K']", 30000, null, "6cd95ed5-8b6f-4f81-8883-3251238ba467");
                _contenttextblock7Info = new RepoItemInfo(this, "ContentTextBlock7", "?/?/text[@name='2K']", "?/?/text[@name='2K']", 30000, null, "7b39ac52-0722-485a-ba98-192c723288ca");
                _navigationautomationidsmainautomationidInfo = new RepoItemInfo(this, "NavigationAutomationIdsMainAutomationId", "list[3]/?/?/radiobutton[@automationid='NavigationAutomationIds.MainAutomationIds.AdvancedFeatures']", ".//radiobutton[@automationid='NavigationAutomationIds.MainAutomationIds.AdvancedFeatures']", 30000, null, "f3bd29c0-b8b0-43a1-affa-7aa0b162eaa4");
                _contenttextblock9Info = new RepoItemInfo(this, "ContentTextBlock9", "?/?/text[@name='4K']", "?/?/text[@name='4K']", 30000, null, "c3e79d8e-5cff-4c00-8e0f-d4c8fd9880ef");
                _contenttextblock10Info = new RepoItemInfo(this, "ContentTextBlock10", "?/?/text[@name='6K']", "?/?/text[@name='6K']", 30000, null, "3f3c9ac6-9cd2-4dfe-9861-83007afa7830");
                _contenttextblock11Info = new RepoItemInfo(this, "ContentTextBlock11", "?/?/text[@name='8K']", "?/?/text[@name='8K']", 30000, null, "6265f4cf-f825-4102-a76b-270da9cd20bb");
                _contenttextblock12Info = new RepoItemInfo(this, "ContentTextBlock12", "?/?/text[@name='CR']", "?/?/text[@name='CR']", 30000, null, "d1bfe751-4cb3-4690-9b57-38b68d30b084");
                _fittingautomationidsadvancedfeaturesautInfo = new RepoItemInfo(this, "FittingAutomationIdsAdvancedFeaturesAut", "?/?/combobox[@automationid='FittingAutomationIds.AdvancedFeaturesAutomationIds.FeatureItemsAutomationIds.Directionality.RIGHT_EAR']", "?/?/combobox[@automationid='FittingAutomationIds.AdvancedFeaturesAutomationIds.FeatureItemsAutomationIds.Directionality.RIGHT_EAR']", 30000, null, "15f7aac0-70a3-443d-b1ea-20990cb3e775");
                _fittingautomationidssaveactionInfo = new RepoItemInfo(this, "FittingAutomationIdsSaveAction", "button[@automationid='FittingAutomationIds.SaveAction']", "button[@automationid='FittingAutomationIds.SaveAction']", 30000, null, "b1dbbe0e-b539-4bf9-b20a-3e7c571bf9d8");
                _partscrollviewerInfo = new RepoItemInfo(this, "PARTScrollViewer", "container[2]", "container[2]", 30000, null, "e9981f07-0eec-47ae-bbc9-758f19a3d76e");
                _menuautomationidsfittingactionInfo = new RepoItemInfo(this, "MenuAutomationIdsFittingAction", "?/?/menuitem[@automationid='MenuAutomationIds.FittingAction']", "?/?/menuitem[@automationid='MenuAutomationIds.FittingAction']", 30000, null, "7ab256bf-d9f0-4f5f-9f32-88ed1d82182a");
                _savedtodatabaseInfo = new RepoItemInfo(this, "SavedToDatabase", "container/text[4]", "container/text[4]", 30000, null, "a4879a91-0e7b-46d5-9b4a-a80fcea49200");
                _saveautomationidsperformsaveautomationi1Info = new RepoItemInfo(this, "SaveAutomationIdsPerformSaveAutomationI1", "button[@automationid='SaveAutomationIds.PerformSaveAutomationIds.ExitAction']", "button[@automationid='SaveAutomationIds.PerformSaveAutomationIds.ExitAction']", 30000, null, "c5fe61cb-d084-4356-912e-4e214d860563");
                _testInfo = new RepoItemInfo(this, "Test", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.EditAction']/text[@name='Test']", ".//text[@name='Test']", 30000, null, "bc6fefc7-ba7e-46a9-a2ae-76b85d219600");
                _patientInfo = new RepoItemInfo(this, "Patient", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.EditAction']/text[@name='Patient']", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.EditAction']/text[@name='Patient']", 30000, null, "3655249e-315a-4018-9864-fcfef51016cb");
                _fitpatientInfo = new RepoItemInfo(this, "FitPatient", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.EditAction']/button[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.FitAction']", ".//button[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.144.Patient.Test.FitAction']", 30000, null, "c7fb3cd2-8853-48f2-9ff6-39e214e50bb8");
                _standaloneautomationidslistautomationidInfo = new RepoItemInfo(this, "StandAloneAutomationIdsListAutomationId", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.145.Patient.Test.EditAction']", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.145.Patient.Test.EditAction']", 30000, null, "5df28b3f-b8dd-4d52-8e17-635febb36aa5");
                _standaloneautomationidslistautomationid1Info = new RepoItemInfo(this, "StandAloneAutomationIdsListAutomationId1", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.EditAction']/button[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.FitAction']", ".//button[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.FitAction']", 30000, null, "66e077f6-2ee9-4fa3-9348-890625e02c64");
                _text3Info = new RepoItemInfo(this, "Text3", ".//button[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.FitAction']/text[@automationid='Text']", ".//text[@name='Fit Patient']", 30000, null, "a76c0138-36f6-4c50-b497-b60e40b404ff");
                _standaloneautomationidslistautomationid2Info = new RepoItemInfo(this, "StandAloneAutomationIdsListAutomationId2", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.EditAction']", "?/?/listitem[@automationid='StandAloneAutomationIds.ListAutomationIds.PatientItemsAutomationIds.142.hii.hello.EditAction']", 30000, null, "3d0bd852-7355-4d5f-bd9e-93958d4847b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9d4415a-519a-4376-a30d-bb92f0511cbd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9d4415a-519a-4376-a30d-bb92f0511cbd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsProfileAutomatio item.
            /// </summary>
            [RepositoryItem("cc32451e-c69a-46dd-9edc-321ab4b650d9")]
            public virtual Ranorex.Text StandAloneAutomationIdsProfileAutomatio
            {
                get
                {
                    return _standaloneautomationidsprofileautomatioInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsProfileAutomatio item info.
            /// </summary>
            [RepositoryItemInfo("cc32451e-c69a-46dd-9edc-321ab4b650d9")]
            public virtual RepoItemInfo StandAloneAutomationIdsProfileAutomatioInfo
            {
                get
                {
                    return _standaloneautomationidsprofileautomatioInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsProfileAutomatio1 item.
            /// </summary>
            [RepositoryItem("1e0c93c9-9477-48f9-9032-385447cc6a24")]
            public virtual Ranorex.Text StandAloneAutomationIdsProfileAutomatio1
            {
                get
                {
                    return _standaloneautomationidsprofileautomatio1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsProfileAutomatio1 item info.
            /// </summary>
            [RepositoryItemInfo("1e0c93c9-9477-48f9-9032-385447cc6a24")]
            public virtual RepoItemInfo StandAloneAutomationIdsProfileAutomatio1Info
            {
                get
                {
                    return _standaloneautomationidsprofileautomatio1Info;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsAdd2Action item.
            /// </summary>
            [RepositoryItem("836c2fbb-932f-413c-bef1-e63fc60abfad")]
            public virtual Ranorex.Button StandAloneAutomationIdsAdd2Action
            {
                get
                {
                    return _standaloneautomationidsadd2actionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsAdd2Action item info.
            /// </summary>
            [RepositoryItemInfo("836c2fbb-932f-413c-bef1-e63fc60abfad")]
            public virtual RepoItemInfo StandAloneAutomationIdsAdd2ActionInfo
            {
                get
                {
                    return _standaloneautomationidsadd2actionInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("51f143a3-1df0-4734-b387-d3ffc3af29b5")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("51f143a3-1df0-4734-b387-d3ffc3af29b5")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ContentTextBlock item.
            /// </summary>
            [RepositoryItem("90070278-86eb-4ad8-abf6-e31d5669d47b")]
            public virtual Ranorex.Text ContentTextBlock
            {
                get
                {
                    return _contenttextblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock item info.
            /// </summary>
            [RepositoryItemInfo("90070278-86eb-4ad8-abf6-e31d5669d47b")]
            public virtual RepoItemInfo ContentTextBlockInfo
            {
                get
                {
                    return _contenttextblockInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsAudiogramAutomat item.
            /// </summary>
            [RepositoryItem("84546401-03d4-4bff-85d0-2adcd0a2157e")]
            public virtual Ranorex.Button StandAloneAutomationIdsAudiogramAutomat
            {
                get
                {
                    return _standaloneautomationidsaudiogramautomatInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsAudiogramAutomat item info.
            /// </summary>
            [RepositoryItemInfo("84546401-03d4-4bff-85d0-2adcd0a2157e")]
            public virtual RepoItemInfo StandAloneAutomationIdsAudiogramAutomatInfo
            {
                get
                {
                    return _standaloneautomationidsaudiogramautomatInfo;
                }
            }

            /// <summary>
            /// The ContentTextBlock1 item.
            /// </summary>
            [RepositoryItem("f20ffcb6-95de-4c0b-83eb-266b9e7a134e")]
            public virtual Ranorex.Text ContentTextBlock1
            {
                get
                {
                    return _contenttextblock1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock1 item info.
            /// </summary>
            [RepositoryItemInfo("f20ffcb6-95de-4c0b-83eb-266b9e7a134e")]
            public virtual RepoItemInfo ContentTextBlock1Info
            {
                get
                {
                    return _contenttextblock1Info;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAction item.
            /// </summary>
            [RepositoryItem("7a87dcaa-fa41-47a7-9a6a-b9967893f094")]
            public virtual Ranorex.MenuItem MenuAutomationIdsViewAction
            {
                get
                {
                    return _menuautomationidsviewactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAction item info.
            /// </summary>
            [RepositoryItemInfo("7a87dcaa-fa41-47a7-9a6a-b9967893f094")]
            public virtual RepoItemInfo MenuAutomationIdsViewActionInfo
            {
                get
                {
                    return _menuautomationidsviewactionInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsDetailsAutomatio1 item.
            /// </summary>
            [RepositoryItem("00b33339-f95d-46d6-9907-a5beb04cbe08")]
            public virtual Ranorex.Button StandAloneAutomationIdsDetailsAutomatio1
            {
                get
                {
                    return _standaloneautomationidsdetailsautomatio1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsDetailsAutomatio1 item info.
            /// </summary>
            [RepositoryItemInfo("00b33339-f95d-46d6-9907-a5beb04cbe08")]
            public virtual RepoItemInfo StandAloneAutomationIdsDetailsAutomatio1Info
            {
                get
                {
                    return _standaloneautomationidsdetailsautomatio1Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("ae7293b6-3b45-46e9-a591-00714a2dcd18")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("ae7293b6-3b45-46e9-a591-00714a2dcd18")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("bbb91551-0ce8-4738-94b6-5da061d7d504")]
            public virtual Ranorex.Text Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("bbb91551-0ce8-4738-94b6-5da061d7d504")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The StateMachineAutomationIdsContinueAction item.
            /// </summary>
            [RepositoryItem("0e429078-8f8c-4b58-ac1b-9ff83b5dcc8d")]
            public virtual Ranorex.Button StateMachineAutomationIdsContinueAction
            {
                get
                {
                    return _statemachineautomationidscontinueactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StateMachineAutomationIdsContinueAction item info.
            /// </summary>
            [RepositoryItemInfo("0e429078-8f8c-4b58-ac1b-9ff83b5dcc8d")]
            public virtual RepoItemInfo StateMachineAutomationIdsContinueActionInfo
            {
                get
                {
                    return _statemachineautomationidscontinueactionInfo;
                }
            }

            /// <summary>
            /// The ContentTextBlock2 item.
            /// </summary>
            [RepositoryItem("f3a1ef92-d0b8-4d54-ae8c-afd1ff9a91e1")]
            public virtual Ranorex.Text ContentTextBlock2
            {
                get
                {
                    return _contenttextblock2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock2 item info.
            /// </summary>
            [RepositoryItemInfo("f3a1ef92-d0b8-4d54-ae8c-afd1ff9a91e1")]
            public virtual RepoItemInfo ContentTextBlock2Info
            {
                get
                {
                    return _contenttextblock2Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock3 item.
            /// </summary>
            [RepositoryItem("44890dbd-7b4e-45d5-b8a4-9bfb248f1687")]
            public virtual Ranorex.Text ContentTextBlock3
            {
                get
                {
                    return _contenttextblock3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock3 item info.
            /// </summary>
            [RepositoryItemInfo("44890dbd-7b4e-45d5-b8a4-9bfb248f1687")]
            public virtual RepoItemInfo ContentTextBlock3Info
            {
                get
                {
                    return _contenttextblock3Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock4 item.
            /// </summary>
            [RepositoryItem("f56f212f-d437-40f4-97a2-0522b4518cc9")]
            public virtual Ranorex.Text ContentTextBlock4
            {
                get
                {
                    return _contenttextblock4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock4 item info.
            /// </summary>
            [RepositoryItemInfo("f56f212f-d437-40f4-97a2-0522b4518cc9")]
            public virtual RepoItemInfo ContentTextBlock4Info
            {
                get
                {
                    return _contenttextblock4Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock5 item.
            /// </summary>
            [RepositoryItem("99e625bd-bdbc-4873-91fc-330505f4e258")]
            public virtual Ranorex.Text ContentTextBlock5
            {
                get
                {
                    return _contenttextblock5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock5 item info.
            /// </summary>
            [RepositoryItemInfo("99e625bd-bdbc-4873-91fc-330505f4e258")]
            public virtual RepoItemInfo ContentTextBlock5Info
            {
                get
                {
                    return _contenttextblock5Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock6 item.
            /// </summary>
            [RepositoryItem("6cd95ed5-8b6f-4f81-8883-3251238ba467")]
            public virtual Ranorex.Text ContentTextBlock6
            {
                get
                {
                    return _contenttextblock6Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock6 item info.
            /// </summary>
            [RepositoryItemInfo("6cd95ed5-8b6f-4f81-8883-3251238ba467")]
            public virtual RepoItemInfo ContentTextBlock6Info
            {
                get
                {
                    return _contenttextblock6Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock7 item.
            /// </summary>
            [RepositoryItem("7b39ac52-0722-485a-ba98-192c723288ca")]
            public virtual Ranorex.Text ContentTextBlock7
            {
                get
                {
                    return _contenttextblock7Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock7 item info.
            /// </summary>
            [RepositoryItemInfo("7b39ac52-0722-485a-ba98-192c723288ca")]
            public virtual RepoItemInfo ContentTextBlock7Info
            {
                get
                {
                    return _contenttextblock7Info;
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item.
            /// </summary>
            [RepositoryItem("f3bd29c0-b8b0-43a1-affa-7aa0b162eaa4")]
            public virtual Ranorex.RadioButton NavigationAutomationIdsMainAutomationId
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The NavigationAutomationIdsMainAutomationId item info.
            /// </summary>
            [RepositoryItemInfo("f3bd29c0-b8b0-43a1-affa-7aa0b162eaa4")]
            public virtual RepoItemInfo NavigationAutomationIdsMainAutomationIdInfo
            {
                get
                {
                    return _navigationautomationidsmainautomationidInfo;
                }
            }

            /// <summary>
            /// The ContentTextBlock9 item.
            /// </summary>
            [RepositoryItem("c3e79d8e-5cff-4c00-8e0f-d4c8fd9880ef")]
            public virtual Ranorex.Text ContentTextBlock9
            {
                get
                {
                    return _contenttextblock9Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock9 item info.
            /// </summary>
            [RepositoryItemInfo("c3e79d8e-5cff-4c00-8e0f-d4c8fd9880ef")]
            public virtual RepoItemInfo ContentTextBlock9Info
            {
                get
                {
                    return _contenttextblock9Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock10 item.
            /// </summary>
            [RepositoryItem("3f3c9ac6-9cd2-4dfe-9861-83007afa7830")]
            public virtual Ranorex.Text ContentTextBlock10
            {
                get
                {
                    return _contenttextblock10Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock10 item info.
            /// </summary>
            [RepositoryItemInfo("3f3c9ac6-9cd2-4dfe-9861-83007afa7830")]
            public virtual RepoItemInfo ContentTextBlock10Info
            {
                get
                {
                    return _contenttextblock10Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock11 item.
            /// </summary>
            [RepositoryItem("6265f4cf-f825-4102-a76b-270da9cd20bb")]
            public virtual Ranorex.Text ContentTextBlock11
            {
                get
                {
                    return _contenttextblock11Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock11 item info.
            /// </summary>
            [RepositoryItemInfo("6265f4cf-f825-4102-a76b-270da9cd20bb")]
            public virtual RepoItemInfo ContentTextBlock11Info
            {
                get
                {
                    return _contenttextblock11Info;
                }
            }

            /// <summary>
            /// The ContentTextBlock12 item.
            /// </summary>
            [RepositoryItem("d1bfe751-4cb3-4690-9b57-38b68d30b084")]
            public virtual Ranorex.Text ContentTextBlock12
            {
                get
                {
                    return _contenttextblock12Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ContentTextBlock12 item info.
            /// </summary>
            [RepositoryItemInfo("d1bfe751-4cb3-4690-9b57-38b68d30b084")]
            public virtual RepoItemInfo ContentTextBlock12Info
            {
                get
                {
                    return _contenttextblock12Info;
                }
            }

            /// <summary>
            /// The FittingAutomationIdsAdvancedFeaturesAut item.
            /// </summary>
            [RepositoryItem("15f7aac0-70a3-443d-b1ea-20990cb3e775")]
            public virtual Ranorex.ComboBox FittingAutomationIdsAdvancedFeaturesAut
            {
                get
                {
                    return _fittingautomationidsadvancedfeaturesautInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The FittingAutomationIdsAdvancedFeaturesAut item info.
            /// </summary>
            [RepositoryItemInfo("15f7aac0-70a3-443d-b1ea-20990cb3e775")]
            public virtual RepoItemInfo FittingAutomationIdsAdvancedFeaturesAutInfo
            {
                get
                {
                    return _fittingautomationidsadvancedfeaturesautInfo;
                }
            }

            /// <summary>
            /// The FittingAutomationIdsSaveAction item.
            /// </summary>
            [RepositoryItem("b1dbbe0e-b539-4bf9-b20a-3e7c571bf9d8")]
            public virtual Ranorex.Button FittingAutomationIdsSaveAction
            {
                get
                {
                    return _fittingautomationidssaveactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FittingAutomationIdsSaveAction item info.
            /// </summary>
            [RepositoryItemInfo("b1dbbe0e-b539-4bf9-b20a-3e7c571bf9d8")]
            public virtual RepoItemInfo FittingAutomationIdsSaveActionInfo
            {
                get
                {
                    return _fittingautomationidssaveactionInfo;
                }
            }

            /// <summary>
            /// The PARTScrollViewer item.
            /// </summary>
            [RepositoryItem("e9981f07-0eec-47ae-bbc9-758f19a3d76e")]
            public virtual Ranorex.Container PARTScrollViewer
            {
                get
                {
                    return _partscrollviewerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTScrollViewer item info.
            /// </summary>
            [RepositoryItemInfo("e9981f07-0eec-47ae-bbc9-758f19a3d76e")]
            public virtual RepoItemInfo PARTScrollViewerInfo
            {
                get
                {
                    return _partscrollviewerInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAction item.
            /// </summary>
            [RepositoryItem("7ab256bf-d9f0-4f5f-9f32-88ed1d82182a")]
            public virtual Ranorex.MenuItem MenuAutomationIdsFittingAction
            {
                get
                {
                    return _menuautomationidsfittingactionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAction item info.
            /// </summary>
            [RepositoryItemInfo("7ab256bf-d9f0-4f5f-9f32-88ed1d82182a")]
            public virtual RepoItemInfo MenuAutomationIdsFittingActionInfo
            {
                get
                {
                    return _menuautomationidsfittingactionInfo;
                }
            }

            /// <summary>
            /// The SavedToDatabase item.
            /// </summary>
            [RepositoryItem("a4879a91-0e7b-46d5-9b4a-a80fcea49200")]
            public virtual Ranorex.Text SavedToDatabase
            {
                get
                {
                    return _savedtodatabaseInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SavedToDatabase item info.
            /// </summary>
            [RepositoryItemInfo("a4879a91-0e7b-46d5-9b4a-a80fcea49200")]
            public virtual RepoItemInfo SavedToDatabaseInfo
            {
                get
                {
                    return _savedtodatabaseInfo;
                }
            }

            /// <summary>
            /// The SaveAutomationIdsPerformSaveAutomationI1 item.
            /// </summary>
            [RepositoryItem("c5fe61cb-d084-4356-912e-4e214d860563")]
            public virtual Ranorex.Button SaveAutomationIdsPerformSaveAutomationI1
            {
                get
                {
                    return _saveautomationidsperformsaveautomationi1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveAutomationIdsPerformSaveAutomationI1 item info.
            /// </summary>
            [RepositoryItemInfo("c5fe61cb-d084-4356-912e-4e214d860563")]
            public virtual RepoItemInfo SaveAutomationIdsPerformSaveAutomationI1Info
            {
                get
                {
                    return _saveautomationidsperformsaveautomationi1Info;
                }
            }

            /// <summary>
            /// The Test item.
            /// </summary>
            [RepositoryItem("bc6fefc7-ba7e-46a9-a2ae-76b85d219600")]
            public virtual Ranorex.Text Test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Test item info.
            /// </summary>
            [RepositoryItemInfo("bc6fefc7-ba7e-46a9-a2ae-76b85d219600")]
            public virtual RepoItemInfo TestInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The Patient item.
            /// </summary>
            [RepositoryItem("3655249e-315a-4018-9864-fcfef51016cb")]
            public virtual Ranorex.Text Patient
            {
                get
                {
                    return _patientInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Patient item info.
            /// </summary>
            [RepositoryItemInfo("3655249e-315a-4018-9864-fcfef51016cb")]
            public virtual RepoItemInfo PatientInfo
            {
                get
                {
                    return _patientInfo;
                }
            }

            /// <summary>
            /// The FitPatient item.
            /// </summary>
            [RepositoryItem("c7fb3cd2-8853-48f2-9ff6-39e214e50bb8")]
            public virtual Ranorex.Button FitPatient
            {
                get
                {
                    return _fitpatientInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FitPatient item info.
            /// </summary>
            [RepositoryItemInfo("c7fb3cd2-8853-48f2-9ff6-39e214e50bb8")]
            public virtual RepoItemInfo FitPatientInfo
            {
                get
                {
                    return _fitpatientInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId item.
            /// </summary>
            [RepositoryItem("5df28b3f-b8dd-4d52-8e17-635febb36aa5")]
            public virtual Ranorex.ListItem StandAloneAutomationIdsListAutomationId
            {
                get
                {
                    return _standaloneautomationidslistautomationidInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId item info.
            /// </summary>
            [RepositoryItemInfo("5df28b3f-b8dd-4d52-8e17-635febb36aa5")]
            public virtual RepoItemInfo StandAloneAutomationIdsListAutomationIdInfo
            {
                get
                {
                    return _standaloneautomationidslistautomationidInfo;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId1 item.
            /// </summary>
            [RepositoryItem("66e077f6-2ee9-4fa3-9348-890625e02c64")]
            public virtual Ranorex.Button StandAloneAutomationIdsListAutomationId1
            {
                get
                {
                    return _standaloneautomationidslistautomationid1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId1 item info.
            /// </summary>
            [RepositoryItemInfo("66e077f6-2ee9-4fa3-9348-890625e02c64")]
            public virtual RepoItemInfo StandAloneAutomationIdsListAutomationId1Info
            {
                get
                {
                    return _standaloneautomationidslistautomationid1Info;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("a76c0138-36f6-4c50-b497-b60e40b404ff")]
            public virtual Ranorex.Text Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("a76c0138-36f6-4c50-b497-b60e40b404ff")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId2 item.
            /// </summary>
            [RepositoryItem("3d0bd852-7355-4d5f-bd9e-93958d4847b9")]
            public virtual Ranorex.ListItem StandAloneAutomationIdsListAutomationId2
            {
                get
                {
                    return _standaloneautomationidslistautomationid2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The StandAloneAutomationIdsListAutomationId2 item info.
            /// </summary>
            [RepositoryItemInfo("3d0bd852-7355-4d5f-bd9e-93958d4847b9")]
            public virtual RepoItemInfo StandAloneAutomationIdsListAutomationId2Info
            {
                get
                {
                    return _standaloneautomationidslistautomationid2Info;
                }
            }
        }

        /// <summary>
        /// The SmartLauncherAppFolder folder.
        /// </summary>
        [RepositoryFolder("9a7a3d65-5cbd-4e5a-954d-c974fef3dab7")]
        public partial class SmartLauncherAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _smartlauncherautomationidssimulateactioInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _windowautomationidscloseactionInfo;
            RepoItemInfo _instrumentmodelInfo;
            RepoItemInfo _resoundlinx3d9Info;
            RepoItemInfo _partfamilygroupsscrollviewerInfo;
            RepoItemInfo _resoundlinx3dInfo;
            RepoItemInfo _parteditorInfo;

            /// <summary>
            /// Creates a new SmartLauncher  folder.
            /// </summary>
            public SmartLauncherAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartLauncher", "/form[@name='Smart Launcher' and @classname='Window' and @orientation='None']", parentFolder, 30000, null, true, "9a7a3d65-5cbd-4e5a-954d-c974fef3dab7", "")
            {
                _smartlauncherautomationidssimulateactioInfo = new RepoItemInfo(this, "SmartLauncherAutomationIdsSimulateActio", "button[@automationid='SmartLauncherAutomationIds.SimulateAction']", "button[@automationid='SmartLauncherAutomationIds.SimulateAction']", 30000, null, "84bd17fa-b6e6-4b2c-a54d-d7b9aad3e6c9");
                _textInfo = new RepoItemInfo(this, "Text", "text[@name='Smart Launcher']", "text[@name='Smart Launcher']", 30000, null, "0393172b-01ff-45f8-a86c-83e66e183186");
                _windowautomationidscloseactionInfo = new RepoItemInfo(this, "WindowAutomationIdsCloseAction", "button[@automationid='WindowAutomationIds.CloseAction']", "button[@automationid='WindowAutomationIds.CloseAction']", 30000, null, "cbd610ce-f128-4d99-9c77-5f3c67383ed9");
                _instrumentmodelInfo = new RepoItemInfo(this, "InstrumentModel", "?/?/text[@name='Instrument Model']", "?/?/text[@name='Instrument Model']", 30000, null, "56f1157d-47ea-4777-ad04-5c3a7b5ec116");
                _resoundlinx3d9Info = new RepoItemInfo(this, "ReSoundLiNX3D9", "?/?/list[@automationid='FamilyListBox']/listitem[@name='ReSound LiNX 3D 9']", ".//listitem[@name='ReSound LiNX 3D 9']", 30000, null, "bccc1e95-733d-4e68-97ee-0019de175471");
                _partfamilygroupsscrollviewerInfo = new RepoItemInfo(this, "PARTFamilyGroupsScrollViewer", "container[@automationid='PART_FamilyGroupsScrollViewer']", "container[@automationid='PART_FamilyGroupsScrollViewer']", 30000, null, "b30424b6-b760-4b2d-8cbc-cf0074868e2c");
                _resoundlinx3dInfo = new RepoItemInfo(this, "ReSoundLiNX3D", "?/?/text[@name='ReSound LiNX 3D']", "?/?/text[@name='ReSound LiNX 3D']", 30000, null, "e621950b-d943-4722-90b5-752e20e4d01d");
                _parteditorInfo = new RepoItemInfo(this, "PARTEditor", "text[@automationid='PART_Editor']", "text[@automationid='PART_Editor']", 30000, null, "55a83cfb-d2e7-41f4-bcfc-d739888b5aef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9a7a3d65-5cbd-4e5a-954d-c974fef3dab7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a7a3d65-5cbd-4e5a-954d-c974fef3dab7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SmartLauncherAutomationIdsSimulateActio item.
            /// </summary>
            [RepositoryItem("84bd17fa-b6e6-4b2c-a54d-d7b9aad3e6c9")]
            public virtual Ranorex.Button SmartLauncherAutomationIdsSimulateActio
            {
                get
                {
                    return _smartlauncherautomationidssimulateactioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SmartLauncherAutomationIdsSimulateActio item info.
            /// </summary>
            [RepositoryItemInfo("84bd17fa-b6e6-4b2c-a54d-d7b9aad3e6c9")]
            public virtual RepoItemInfo SmartLauncherAutomationIdsSimulateActioInfo
            {
                get
                {
                    return _smartlauncherautomationidssimulateactioInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("0393172b-01ff-45f8-a86c-83e66e183186")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("0393172b-01ff-45f8-a86c-83e66e183186")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The WindowAutomationIdsCloseAction item.
            /// </summary>
            [RepositoryItem("cbd610ce-f128-4d99-9c77-5f3c67383ed9")]
            public virtual Ranorex.Button WindowAutomationIdsCloseAction
            {
                get
                {
                    return _windowautomationidscloseactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The WindowAutomationIdsCloseAction item info.
            /// </summary>
            [RepositoryItemInfo("cbd610ce-f128-4d99-9c77-5f3c67383ed9")]
            public virtual RepoItemInfo WindowAutomationIdsCloseActionInfo
            {
                get
                {
                    return _windowautomationidscloseactionInfo;
                }
            }

            /// <summary>
            /// The InstrumentModel item.
            /// </summary>
            [RepositoryItem("56f1157d-47ea-4777-ad04-5c3a7b5ec116")]
            public virtual Ranorex.Text InstrumentModel
            {
                get
                {
                    return _instrumentmodelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InstrumentModel item info.
            /// </summary>
            [RepositoryItemInfo("56f1157d-47ea-4777-ad04-5c3a7b5ec116")]
            public virtual RepoItemInfo InstrumentModelInfo
            {
                get
                {
                    return _instrumentmodelInfo;
                }
            }

            /// <summary>
            /// The ReSoundLiNX3D9 item.
            /// </summary>
            [RepositoryItem("bccc1e95-733d-4e68-97ee-0019de175471")]
            public virtual Ranorex.ListItem ReSoundLiNX3D9
            {
                get
                {
                    return _resoundlinx3d9Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ReSoundLiNX3D9 item info.
            /// </summary>
            [RepositoryItemInfo("bccc1e95-733d-4e68-97ee-0019de175471")]
            public virtual RepoItemInfo ReSoundLiNX3D9Info
            {
                get
                {
                    return _resoundlinx3d9Info;
                }
            }

            /// <summary>
            /// The PARTFamilyGroupsScrollViewer item.
            /// </summary>
            [RepositoryItem("b30424b6-b760-4b2d-8cbc-cf0074868e2c")]
            public virtual Ranorex.Container PARTFamilyGroupsScrollViewer
            {
                get
                {
                    return _partfamilygroupsscrollviewerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTFamilyGroupsScrollViewer item info.
            /// </summary>
            [RepositoryItemInfo("b30424b6-b760-4b2d-8cbc-cf0074868e2c")]
            public virtual RepoItemInfo PARTFamilyGroupsScrollViewerInfo
            {
                get
                {
                    return _partfamilygroupsscrollviewerInfo;
                }
            }

            /// <summary>
            /// The ReSoundLiNX3D item.
            /// </summary>
            [RepositoryItem("e621950b-d943-4722-90b5-752e20e4d01d")]
            public virtual Ranorex.Text ReSoundLiNX3D
            {
                get
                {
                    return _resoundlinx3dInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ReSoundLiNX3D item info.
            /// </summary>
            [RepositoryItemInfo("e621950b-d943-4722-90b5-752e20e4d01d")]
            public virtual RepoItemInfo ReSoundLiNX3DInfo
            {
                get
                {
                    return _resoundlinx3dInfo;
                }
            }

            /// <summary>
            /// The PARTEditor item.
            /// </summary>
            [RepositoryItem("55a83cfb-d2e7-41f4-bcfc-d739888b5aef")]
            public virtual Ranorex.Text PARTEditor
            {
                get
                {
                    return _parteditorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PARTEditor item info.
            /// </summary>
            [RepositoryItemInfo("55a83cfb-d2e7-41f4-bcfc-d739888b5aef")]
            public virtual RepoItemInfo PARTEditorInfo
            {
                get
                {
                    return _parteditorInfo;
                }
            }
        }

        /// <summary>
        /// The SmartFitAppFolder folder.
        /// </summary>
        [RepositoryFolder("38008620-1f1a-4578-b6a6-eefb8e3b7d4e")]
        public partial class SmartFitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuautomationidsviewautomationidscoup1Info;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _menuautomationidsviewautomationidscoup2Info;
            RepoItemInfo _somelistitemInfo;
            RepoItemInfo _sideradiobuttonInfo;
            RepoItemInfo _somecontainer1Info;
            RepoItemInfo _someelement1Info;
            RepoItemInfo _fittingautomationidsadvancedfeaturesautInfo;
            RepoItemInfo _menuautomationidsfittingautomationidsrInfo;

            /// <summary>
            /// Creates a new SmartFit  folder.
            /// </summary>
            public SmartFitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SmartFit", "/contextmenu[@automationid='' and @wpfnative='True']", parentFolder, 30000, null, false, "38008620-1f1a-4578-b6a6-eefb8e3b7d4e", "")
            {
                _menuautomationidsviewautomationidscoup1Info = new RepoItemInfo(this, "MenuAutomationIdsViewAutomationIdsCoup1", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerActionItemsAutomationIds.InsertionGain']", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerActionItemsAutomationIds.InsertionGain']", 30000, null, "1230175b-bb3b-4e7a-80a6-abde14e40479");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.LanguageActionItemsAutomationIds.bg-BG']/?/?/element", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.LanguageActionItemsAutomationIds.bg-BG']/element[@automationid='GeometryContentControl']/element", 30000, null, "bd1372d6-c1c4-4631-bead-0f4b33814157");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerAction']/container", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerAction']/container", 30000, null, "41431212-ff16-47e9-96d8-08a86b4d381c");
                _menuautomationidsviewautomationidscoup2Info = new RepoItemInfo(this, "MenuAutomationIdsViewAutomationIdsCoup2", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerActionItemsAutomationIds.TwoCCGain']", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerActionItemsAutomationIds.TwoCCGain']", 30000, null, "738dd655-9942-43fc-8b5f-811815731f97");
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", "list//listitem[@index='0']/?/?/container[@automationid='ProductDetailsGrid']/list/?/?/listitem[@index='1']", ".//listitem[@index='1']", 30000, null, "dcb8ef2d-c09f-45a8-b443-b265e0c98194");
                _sideradiobuttonInfo = new RepoItemInfo(this, "SideRadioButton", "list//container[@automationid='ProductDetailsGrid']/list/?/?/listitem[@index='1']/radiobutton[@automationid='SideRadioButton']", ".//radiobutton[@name='SideRadioButton' and @text='Both']", 30000, null, "b59e15e8-edf5-48eb-9eef-1611ee0679eb");
                _somecontainer1Info = new RepoItemInfo(this, "SomeContainer1", "list//listitem[@index='0']/container", ".//listitem/container", 30000, null, "29bc992c-b9de-4f0e-8feb-c34bd5b2fc07");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerAction']/container/element[@automationid='GeometryContentControl']/element", "menuitem[@automationid='MenuAutomationIds.ViewAutomationIds.CouplerAction']/container/element[@automationid='GeometryContentControl']/element", 30000, null, "b046927d-1556-49e9-b756-f4fd8e9b7e75");
                _fittingautomationidsadvancedfeaturesautInfo = new RepoItemInfo(this, "FittingAutomationIdsAdvancedFeaturesAut", "listitem[@automationid='FittingAutomationIds.AdvancedFeaturesAutomationIds.FeatureItemsAutomationIds.Directionality.Omni.RIGHT_EAR']", "listitem[@automationid='FittingAutomationIds.AdvancedFeaturesAutomationIds.FeatureItemsAutomationIds.Directionality.Omni.RIGHT_EAR']", 30000, null, "932b714e-657e-4c7a-8569-8f5678e7d622");
                _menuautomationidsfittingautomationidsrInfo = new RepoItemInfo(this, "MenuAutomationIdsFittingAutomationIdsR", "menuitem[@automationid='MenuAutomationIds.FittingAutomationIds.ResetAutomationIds.InitialFitAction']", "menuitem[@automationid='MenuAutomationIds.FittingAutomationIds.ResetAutomationIds.InitialFitAction']", 30000, null, "74020028-93a4-4e10-a397-bf9a1c777d4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("38008620-1f1a-4578-b6a6-eefb8e3b7d4e")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("38008620-1f1a-4578-b6a6-eefb8e3b7d4e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAutomationIdsCoup1 item.
            /// </summary>
            [RepositoryItem("1230175b-bb3b-4e7a-80a6-abde14e40479")]
            public virtual Ranorex.MenuItem MenuAutomationIdsViewAutomationIdsCoup1
            {
                get
                {
                    return _menuautomationidsviewautomationidscoup1Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAutomationIdsCoup1 item info.
            /// </summary>
            [RepositoryItemInfo("1230175b-bb3b-4e7a-80a6-abde14e40479")]
            public virtual RepoItemInfo MenuAutomationIdsViewAutomationIdsCoup1Info
            {
                get
                {
                    return _menuautomationidsviewautomationidscoup1Info;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("bd1372d6-c1c4-4631-bead-0f4b33814157")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("bd1372d6-c1c4-4631-bead-0f4b33814157")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("41431212-ff16-47e9-96d8-08a86b4d381c")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("41431212-ff16-47e9-96d8-08a86b4d381c")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAutomationIdsCoup2 item.
            /// </summary>
            [RepositoryItem("738dd655-9942-43fc-8b5f-811815731f97")]
            public virtual Ranorex.MenuItem MenuAutomationIdsViewAutomationIdsCoup2
            {
                get
                {
                    return _menuautomationidsviewautomationidscoup2Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsViewAutomationIdsCoup2 item info.
            /// </summary>
            [RepositoryItemInfo("738dd655-9942-43fc-8b5f-811815731f97")]
            public virtual RepoItemInfo MenuAutomationIdsViewAutomationIdsCoup2Info
            {
                get
                {
                    return _menuautomationidsviewautomationidscoup2Info;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("dcb8ef2d-c09f-45a8-b443-b265e0c98194")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("dcb8ef2d-c09f-45a8-b443-b265e0c98194")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }

            /// <summary>
            /// The SideRadioButton item.
            /// </summary>
            [RepositoryItem("b59e15e8-edf5-48eb-9eef-1611ee0679eb")]
            public virtual Ranorex.RadioButton SideRadioButton
            {
                get
                {
                    return _sideradiobuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SideRadioButton item info.
            /// </summary>
            [RepositoryItemInfo("b59e15e8-edf5-48eb-9eef-1611ee0679eb")]
            public virtual RepoItemInfo SideRadioButtonInfo
            {
                get
                {
                    return _sideradiobuttonInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 item.
            /// </summary>
            [RepositoryItem("29bc992c-b9de-4f0e-8feb-c34bd5b2fc07")]
            public virtual Ranorex.Container SomeContainer1
            {
                get
                {
                    return _somecontainer1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer1 item info.
            /// </summary>
            [RepositoryItemInfo("29bc992c-b9de-4f0e-8feb-c34bd5b2fc07")]
            public virtual RepoItemInfo SomeContainer1Info
            {
                get
                {
                    return _somecontainer1Info;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("b046927d-1556-49e9-b756-f4fd8e9b7e75")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("b046927d-1556-49e9-b756-f4fd8e9b7e75")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }

            /// <summary>
            /// The FittingAutomationIdsAdvancedFeaturesAut item.
            /// </summary>
            [RepositoryItem("932b714e-657e-4c7a-8569-8f5678e7d622")]
            public virtual Ranorex.ListItem FittingAutomationIdsAdvancedFeaturesAut
            {
                get
                {
                    return _fittingautomationidsadvancedfeaturesautInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The FittingAutomationIdsAdvancedFeaturesAut item info.
            /// </summary>
            [RepositoryItemInfo("932b714e-657e-4c7a-8569-8f5678e7d622")]
            public virtual RepoItemInfo FittingAutomationIdsAdvancedFeaturesAutInfo
            {
                get
                {
                    return _fittingautomationidsadvancedfeaturesautInfo;
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAutomationIdsR item.
            /// </summary>
            [RepositoryItem("74020028-93a4-4e10-a397-bf9a1c777d4f")]
            public virtual Ranorex.MenuItem MenuAutomationIdsFittingAutomationIdsR
            {
                get
                {
                    return _menuautomationidsfittingautomationidsrInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuAutomationIdsFittingAutomationIdsR item info.
            /// </summary>
            [RepositoryItemInfo("74020028-93a4-4e10-a397-bf9a1c777d4f")]
            public virtual RepoItemInfo MenuAutomationIdsFittingAutomationIdsRInfo
            {
                get
                {
                    return _menuautomationidsfittingautomationidsrInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("14e0119e-0a45-4136-9024-cf59fbb8a5c2")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _launchfswranorexstudio32bitInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@title='']", parentFolder, 30000, null, true, "14e0119e-0a45-4136-9024-cf59fbb8a5c2", "")
            {
                _launchfswranorexstudio32bitInfo = new RepoItemInfo(this, "LaunchFSWRanorexStudio32bit", "?/?/listitem[@accessiblename>'LaunchFSW - Ranorex Studio']", "?/?/listitem[@accessiblename>'LaunchFSW - Ranorex Studio']", 30000, null, "e87b7d56-29b2-40c2-b59e-e3e1c5cda498");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("14e0119e-0a45-4136-9024-cf59fbb8a5c2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("14e0119e-0a45-4136-9024-cf59fbb8a5c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LaunchFSWRanorexStudio32bit item.
            /// </summary>
            [RepositoryItem("e87b7d56-29b2-40c2-b59e-e3e1c5cda498")]
            public virtual Ranorex.ListItem LaunchFSWRanorexStudio32bit
            {
                get
                {
                    return _launchfswranorexstudio32bitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The LaunchFSWRanorexStudio32bit item info.
            /// </summary>
            [RepositoryItemInfo("e87b7d56-29b2-40c2-b59e-e3e1c5cda498")]
            public virtual RepoItemInfo LaunchFSWRanorexStudio32bitInfo
            {
                get
                {
                    return _launchfswranorexstudio32bitInfo;
                }
            }
        }

        /// <summary>
        /// The TargetViewerAppFolder folder.
        /// </summary>
        [RepositoryFolder("30213608-5b5a-467d-90fd-56a7f6a575c1")]
        public partial class TargetViewerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _datagridInfo;
            RepoItemInfo _pathclosebuttonInfo;

            /// <summary>
            /// Creates a new TargetViewer  folder.
            /// </summary>
            public TargetViewerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TargetViewer", "/form[@name='Target Viewer' and @classname='Window' and @orientation='None']", parentFolder, 30000, null, true, "30213608-5b5a-467d-90fd-56a7f6a575c1", "")
            {
                _datagridInfo = new RepoItemInfo(this, "DataGrid", "?/?/tabpagelist/tabpage[1]/container[@automationid='MainScrollViewer']/table[3]", ".//container/table[3]", 30000, null, "408104b9-101e-489b-96f8-23b43750d59a");
                _pathclosebuttonInfo = new RepoItemInfo(this, "PATHCloseButton", "button[@automationid='PATH_CloseButton']", "button[@automationid='PATH_CloseButton']", 30000, null, "d4d2e8a2-a82b-48ac-a2d1-74162471c715");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("30213608-5b5a-467d-90fd-56a7f6a575c1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("30213608-5b5a-467d-90fd-56a7f6a575c1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DataGrid item.
            /// </summary>
            [RepositoryItem("408104b9-101e-489b-96f8-23b43750d59a")]
            public virtual Ranorex.Table DataGrid
            {
                get
                {
                    return _datagridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The DataGrid item info.
            /// </summary>
            [RepositoryItemInfo("408104b9-101e-489b-96f8-23b43750d59a")]
            public virtual RepoItemInfo DataGridInfo
            {
                get
                {
                    return _datagridInfo;
                }
            }

            /// <summary>
            /// The PATHCloseButton item.
            /// </summary>
            [RepositoryItem("d4d2e8a2-a82b-48ac-a2d1-74162471c715")]
            public virtual Ranorex.Button PATHCloseButton
            {
                get
                {
                    return _pathclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PATHCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("d4d2e8a2-a82b-48ac-a2d1-74162471c715")]
            public virtual RepoItemInfo PATHCloseButtonInfo
            {
                get
                {
                    return _pathclosebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The WindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("3e58e746-2d81-46bf-82a4-e42589f514c9")]
        public partial class WindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _expanderInfo;
            RepoItemInfo _maximizeInfo;
            RepoItemInfo _expander1Info;
            RepoItemInfo _expander2Info;
            RepoItemInfo _expander3Info;
            RepoItemInfo _directionalityInfo;
            RepoItemInfo _expander4Info;
            RepoItemInfo _expander5Info;
            RepoItemInfo _expander6Info;
            RepoItemInfo _expander7Info;
            RepoItemInfo _expander8Info;
            RepoItemInfo _dialogautomationidspositiveactionInfo;

            /// <summary>
            /// Creates a new Window  folder.
            /// </summary>
            public WindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Window", "/form[@orientation='None' and @automationid='']", parentFolder, 30000, null, true, "3e58e746-2d81-46bf-82a4-e42589f514c9", "")
            {
                _expanderInfo = new RepoItemInfo(this, "Expander", "tree[@automationid='DomainTreeView']/treeitem[@name='Active Product Left']/button[@automationid='Expander']", "?/?/treeitem[@name='Active Product Left']/button[@automationid='Expander']", 30000, null, "ec9fa989-101f-4b48-8541-43417c6dc3e1");
                _maximizeInfo = new RepoItemInfo(this, "Maximize", "?/?/button[@automationid='Maximize']", "?/?/button[@automationid='Maximize']", 30000, null, "f7139f1b-04c3-4322-b5b1-e7c2f9ee110e");
                _expander1Info = new RepoItemInfo(this, "Expander1", ".//treeitem[@automationid='AvailablePrograms']/button[@automationid='Expander']", ".//treeitem[@automationid='AvailablePrograms']/button[@automationid='Expander']", 30000, null, "bbe5f9ac-2629-4a13-a03f-610ed9273fbf");
                _expander2Info = new RepoItemInfo(this, "Expander2", "tree[@automationid='DomainTreeView']/?/?/treeitem[@automationid='AvailablePrograms']/?/?/button[@automationid='Expander']", ".//treeitem[@automationid='AvailablePrograms']/treeitem[1]/button[@automationid='Expander']", 30000, null, "01bdc7d9-c52e-44bd-b7e8-35b772bd3889");
                _expander3Info = new RepoItemInfo(this, "Expander3", ".//treeitem[@automationid='AvailablePrograms']/?/?/treeitem[@automationid='Features']/button[@automationid='Expander']", ".//treeitem[@name='Features, Count : 47']/button[@automationid='Expander']", 30000, null, "6a0740ac-95fd-4386-81b9-ccc805487eea");
                _directionalityInfo = new RepoItemInfo(this, "Directionality", "tree[@automationid='DomainTreeView']/?/?/treeitem[@automationid='AvailablePrograms']/?/?/treeitem[@automationid='Features']/?/?/text[@name='Directionality']", ".//text[@name='Directionality']", 30000, null, "db7e1f6c-b155-4e46-8998-dfc46421a55b");
                _expander4Info = new RepoItemInfo(this, "Expander4", "tree[@automationid='DomainTreeView']/?/?/treeitem[@automationid='AvailablePrograms']/?/?/treeitem[@automationid='Features']/treeitem[@name='Directionality']/button[@automationid='Expander']", ".//treeitem[@name='Directionality']/button[@automationid='Expander']", 30000, null, "ddce36f0-3fc9-4535-ba39-9a8dcfef9036");
                _expander5Info = new RepoItemInfo(this, "Expander5", ".//treeitem[@automationid='AllPrograms']/button[@automationid='Expander']", ".//treeitem[@automationid='AllPrograms']/button[@automationid='Expander']", 30000, null, "076905ed-4b9d-463c-87a4-dd3695c3052f");
                _expander6Info = new RepoItemInfo(this, "Expander6", "tree[@automationid='DomainTreeView']/?/?/treeitem[@automationid='AllPrograms']/treeitem[1]/button[@automationid='Expander']", ".//treeitem[@automationid='AllPrograms']/treeitem[1]/button[@automationid='Expander']", 30000, null, "d3fdd762-6f67-4a3a-9e16-3bb19a874906");
                _expander7Info = new RepoItemInfo(this, "Expander7", ".//treeitem[@automationid='AllPrograms']/?/?/treeitem[@automationid='Features']/button[@automationid='Expander']", ".//treeitem[@name='Features, Count : 47']/button[@automationid='Expander']", 30000, null, "5bc3cf51-95ac-45bb-813e-7ec0827e84b2");
                _expander8Info = new RepoItemInfo(this, "Expander8", "tree[@automationid='DomainTreeView']/?/?/treeitem[@automationid='AllPrograms']/?/?/treeitem[@automationid='Features']/?/?/button[@classname='Button' and @orientation='None' and @iscontentelement='True']", ".//treeitem[@name='Directionality']/button[@automationid='Expander']", 30000, null, "d723a4a4-a08a-455e-9435-cf4ba1eb9201");
                _dialogautomationidspositiveactionInfo = new RepoItemInfo(this, "DialogAutomationIdsPositiveAction", "button[@automationid='DialogAutomationIds.PositiveAction']", "button[@automationid='DialogAutomationIds.PositiveAction']", 30000, null, "f4ce56fa-32e6-4386-b5b0-ff0141878088");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e58e746-2d81-46bf-82a4-e42589f514c9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e58e746-2d81-46bf-82a4-e42589f514c9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Expander item.
            /// </summary>
            [RepositoryItem("ec9fa989-101f-4b48-8541-43417c6dc3e1")]
            public virtual Ranorex.Button Expander
            {
                get
                {
                    return _expanderInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander item info.
            /// </summary>
            [RepositoryItemInfo("ec9fa989-101f-4b48-8541-43417c6dc3e1")]
            public virtual RepoItemInfo ExpanderInfo
            {
                get
                {
                    return _expanderInfo;
                }
            }

            /// <summary>
            /// The Maximize item.
            /// </summary>
            [RepositoryItem("f7139f1b-04c3-4322-b5b1-e7c2f9ee110e")]
            public virtual Ranorex.Button Maximize
            {
                get
                {
                    return _maximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Maximize item info.
            /// </summary>
            [RepositoryItemInfo("f7139f1b-04c3-4322-b5b1-e7c2f9ee110e")]
            public virtual RepoItemInfo MaximizeInfo
            {
                get
                {
                    return _maximizeInfo;
                }
            }

            /// <summary>
            /// The Expander1 item.
            /// </summary>
            [RepositoryItem("bbe5f9ac-2629-4a13-a03f-610ed9273fbf")]
            public virtual Ranorex.Button Expander1
            {
                get
                {
                    return _expander1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander1 item info.
            /// </summary>
            [RepositoryItemInfo("bbe5f9ac-2629-4a13-a03f-610ed9273fbf")]
            public virtual RepoItemInfo Expander1Info
            {
                get
                {
                    return _expander1Info;
                }
            }

            /// <summary>
            /// The Expander2 item.
            /// </summary>
            [RepositoryItem("01bdc7d9-c52e-44bd-b7e8-35b772bd3889")]
            public virtual Ranorex.Button Expander2
            {
                get
                {
                    return _expander2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander2 item info.
            /// </summary>
            [RepositoryItemInfo("01bdc7d9-c52e-44bd-b7e8-35b772bd3889")]
            public virtual RepoItemInfo Expander2Info
            {
                get
                {
                    return _expander2Info;
                }
            }

            /// <summary>
            /// The Expander3 item.
            /// </summary>
            [RepositoryItem("6a0740ac-95fd-4386-81b9-ccc805487eea")]
            public virtual Ranorex.Button Expander3
            {
                get
                {
                    return _expander3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander3 item info.
            /// </summary>
            [RepositoryItemInfo("6a0740ac-95fd-4386-81b9-ccc805487eea")]
            public virtual RepoItemInfo Expander3Info
            {
                get
                {
                    return _expander3Info;
                }
            }

            /// <summary>
            /// The Directionality item.
            /// </summary>
            [RepositoryItem("db7e1f6c-b155-4e46-8998-dfc46421a55b")]
            public virtual Ranorex.Text Directionality
            {
                get
                {
                    return _directionalityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Directionality item info.
            /// </summary>
            [RepositoryItemInfo("db7e1f6c-b155-4e46-8998-dfc46421a55b")]
            public virtual RepoItemInfo DirectionalityInfo
            {
                get
                {
                    return _directionalityInfo;
                }
            }

            /// <summary>
            /// The Expander4 item.
            /// </summary>
            [RepositoryItem("ddce36f0-3fc9-4535-ba39-9a8dcfef9036")]
            public virtual Ranorex.Button Expander4
            {
                get
                {
                    return _expander4Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander4 item info.
            /// </summary>
            [RepositoryItemInfo("ddce36f0-3fc9-4535-ba39-9a8dcfef9036")]
            public virtual RepoItemInfo Expander4Info
            {
                get
                {
                    return _expander4Info;
                }
            }

            /// <summary>
            /// The Expander5 item.
            /// </summary>
            [RepositoryItem("076905ed-4b9d-463c-87a4-dd3695c3052f")]
            public virtual Ranorex.Button Expander5
            {
                get
                {
                    return _expander5Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander5 item info.
            /// </summary>
            [RepositoryItemInfo("076905ed-4b9d-463c-87a4-dd3695c3052f")]
            public virtual RepoItemInfo Expander5Info
            {
                get
                {
                    return _expander5Info;
                }
            }

            /// <summary>
            /// The Expander6 item.
            /// </summary>
            [RepositoryItem("d3fdd762-6f67-4a3a-9e16-3bb19a874906")]
            public virtual Ranorex.Button Expander6
            {
                get
                {
                    return _expander6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander6 item info.
            /// </summary>
            [RepositoryItemInfo("d3fdd762-6f67-4a3a-9e16-3bb19a874906")]
            public virtual RepoItemInfo Expander6Info
            {
                get
                {
                    return _expander6Info;
                }
            }

            /// <summary>
            /// The Expander7 item.
            /// </summary>
            [RepositoryItem("5bc3cf51-95ac-45bb-813e-7ec0827e84b2")]
            public virtual Ranorex.Button Expander7
            {
                get
                {
                    return _expander7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander7 item info.
            /// </summary>
            [RepositoryItemInfo("5bc3cf51-95ac-45bb-813e-7ec0827e84b2")]
            public virtual RepoItemInfo Expander7Info
            {
                get
                {
                    return _expander7Info;
                }
            }

            /// <summary>
            /// The Expander8 item.
            /// </summary>
            [RepositoryItem("d723a4a4-a08a-455e-9435-cf4ba1eb9201")]
            public virtual Ranorex.Button Expander8
            {
                get
                {
                    return _expander8Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Expander8 item info.
            /// </summary>
            [RepositoryItemInfo("d723a4a4-a08a-455e-9435-cf4ba1eb9201")]
            public virtual RepoItemInfo Expander8Info
            {
                get
                {
                    return _expander8Info;
                }
            }

            /// <summary>
            /// The DialogAutomationIdsPositiveAction item.
            /// </summary>
            [RepositoryItem("f4ce56fa-32e6-4386-b5b0-ff0141878088")]
            public virtual Ranorex.Button DialogAutomationIdsPositiveAction
            {
                get
                {
                    return _dialogautomationidspositiveactionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DialogAutomationIdsPositiveAction item info.
            /// </summary>
            [RepositoryItemInfo("f4ce56fa-32e6-4386-b5b0-ff0141878088")]
            public virtual RepoItemInfo DialogAutomationIdsPositiveActionInfo
            {
                get
                {
                    return _dialogautomationidspositiveactionInfo;
                }
            }
        }

        /// <summary>
        /// The SomeFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf40f161-549b-409f-b42e-90ee0284e7c4")]
        public partial class SomeFormAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SomeForm  folder.
            /// </summary>
            public SomeFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeForm", "/form", parentFolder, 30000, null, true, "cf40f161-549b-409f-b42e-90ee0284e7c4", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf40f161-549b-409f-b42e-90ee0284e7c4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf40f161-549b-409f-b42e-90ee0284e7c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
